FileVersion = 1

[Project]
Name = "iniparser-beef"
DefaultNamespace = "iniparser"

[Configs.Debug.Win64]
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\iniparser_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\iniparser.lib"]
